#!/bin/bash

# Parse cmdline args.
# Demonstrate if-else control flow in bash scripting.

print_usage() {
	echo "Usage: >\$ $0 <arg>" 1>&2
	exit 1
}

# START

if [ $# -ne 1 ]; then
	print_usage
else
	echo "entered arg: $1"
fi

printf "End of script. Exiting...\n"