#!/bin/bash
# shell scripting for-loop example.

echo "Bash v${BASH_VERSION}"

# ----------- #
# ranged loop #
# ----------- #
for n in {1..10}
do
    # ----------------------- #
    # if statements:          #
    # shell vs. c-like syntax #
    # ----------------------- #
    if [ $n -lt 5 ]; then
        echo "$n"
    else
        if (("$n" > 5))
        then
            echo ${n}
        fi
    fi
done
