#!/bin/bash
# Enter new brightness value as arg.
# Similar to my other script, chBrightness,
# but quicker/more convenient?

NEW_BRIGHTNESS=$1
CURRENT_BRIGHTNESS=$(xfpm-power-backlight-helper --get-brightness)
FLOOR=100															# Don't let the user set brightness lower than 100.
MAX_BRIGHTNESS=24000

function usage() {
	echo "Usage:\n>$ brightness <100-24000>"
	echo "Current Brightness: ${CURRENT_BRIGHTNESS}"
	echo "Max Brightness: ${MAX_BRIGHTNESS}"
}

if [ $# -lt 1 ] || [ $# -gt 1 ]
then
	usage
	exit
fi

if [ $1 -gt ${FLOOR} ] && [ $1 -lt $MAX_BRIGHTNESS ]
then
	pkexec xfpm-power-backlight-helper --set-brightness ${NEW_BRIGHTNESS}
fi
