#!/usr/bin/env bash
# -----------------
# catmail.sh
# -----------------
# Personal use.
# Concatonate (append) 'mbox' files created
# by system mail to a master file I have set
# aside.
# brianc2788@gmail.com
# -----------------
cat ~/mbox >> ~/Documents/system/mbox.copy && rm ~/mbox
