#! /usr/bin/env bash
echo 'change brightness on this laptop'
echo 'brightness value must be between'
echo '0 (min brightness) and 24000 (max)'
echo 'enter brightness:'

read BRIGHTNESS

pkexec xfpm-power-backlight-helper --set-brightness $BRIGHTNESS

