#! /usr/bin/env bash
printf 'change brightness on this laptop\n'
printf 'brightness value must be between\n'
printf '0 (min brightness) and 24000 (max)\n'
printf '\---------------------------------- \n'
printf 'current brightness:'
xfpm-power-backlight-helper --get-brightness
printf 'enter brightness:'

read BRIGHTNESS

pkexec xfpm-power-backlight-helper --set-brightness $BRIGHTNESS

