#!/bin/bash
# Checks the 'ip_forward' network rule on linux.
# requires root permissions.

printf "[i]Reading from '/proc/sys/net/ipv4/ip_forward'....\n\n"
cat /proc/sys/net/ipv4/ip_forward

printf "\n[i]RESULTS OF 'ip netconf'.......\n\n"
ip netconf | head -n5
# only display ipv4 config. 
