#!/usr/bin/bash
# claim file ownership (user, group).
# privileges required to modify another user's file(s).
# using sudo in the script, for now.

function claimfile() {
	filename=$1
	sudo chown $(id -un) ${filename}
	chgrp $(id -gn) ${filename}
}

function printUsage() {
	echo -e "Usage: $(basename $0) file [file2 file3 [...]]"
}

if [ $# -lt 1 ];then
	echo "Please specify a file to claim."
	#echo -e "Usage\nuser@local$ $(basename $0) file [file2 file3 [...]]"
	printUsage
	exit 0
fi

for file in $@
do
	if [ -e ${file} ];then
		claimfile ${file}
	else
		echo "Couldn't locate your file: ${file}"
	fi
done

