#!/bin/bash
# epochdiff.sh
# ------------
# Uses gnu 'date' to convert 'seconds since
# the epoch' (00:00AM, Jan 1, 1970), then
# calculates the difference with shell arithmetic.
# http://brianc2788.github.io/


## globals

EPOCH_NOW=$(date +%s)

function usage() {
	echo -e "Usage:\nsuser@local$ epochdiff epoch1 [epoch2] [...]"
	exit 0
}


function printDifference() {
	local -i nArg=$1
	local -i nEpoch=$2
	local -i DIFF=0
	local DateString=$(date --date=@${nArg} +"%b %_d, %Y at %r")
	if [ ${nArg} -gt ${nEpoch} ];then
		DIFF=${nArg}-${nEpoch}
		echo ${DIFF}
	elif [ ${nArg} -lt ${nEpoch} ];then
		DIFF=${nEpoch}-${nArg}
		echo "${DIFF} seconds since ${DateString}"
	fi
}

## main
# loop argv.
if [ $# -lt 1 ];then
	echo "Current seconds since the epoch: ${EPOCH_NOW}"
	usage
else
	echo "Current Epoch: ${EPOCH_NOW}"
fi

# Loop through arguments with print_diff().
for arg in $@
do
	printDifference ${arg} ${EPOCH_NOW}
done

exit 0
