#!/bin/bash
# ===========================================
# gitstat
# --------
# Bash script for personal use.
# Calls 'git-status' in each of my local
# repositories for untracked changes.
# --------
# Authored by brianc2788@gmail.com
# http://user5260.github.io
# ===========================================

# TODO:
# - everything.

ROOT_DIR="${HOME}/dev"

if [ ]
echo ${ROOT_DIR}