#!/usr/bin/env bash
# -----------------
# logmail.sh
# -----------------
# Personal use.
# Log files created by system mail
# to a master file I have set aside.
# http://brianc2788.github.io/
# -----------------
FILE_MBOX=${HOME}/mbox
LOG_DEST=${HOME}/Documents/sys/mbox.copy

# True if file exists (-a or -e)
if [ -e ${FILE_MBOX} ];then
	cat ${FILE_MBOX} >> ${LOG_DEST} && rm ${FILE_MBOX}
	echo "[i] Copied contents of 'mbox' to ${LOG_DEST}"

	if [ ! -e ${FILE_MBOX} ];then
		echo "[i] Deleted file: /home/userone/mbox"
	else
		echo -e "[!] Couldn't delete ${FILE_MBOX};\nFile is still present in ${HOME}."
		exit 1
	fi
else
	echo -e "[!] Couldn't find ${FILE_MBOX} in ${HOME}.\nAborting..."
	exit 1
fi
