#!/usr/bin/env bash
# -----------------
# catmail.sh
# -----------------
# Personal use.
# Concatonate (append) 'mbox' files created
# by system mail to a master file I have set
# aside.
# brianc2788@gmail.com
# -----------------
TMP_MBOX=${HOME}/mbox
LOG_DEST=${HOME}/Documents/system/mbox.copy

# True if file exists (-a or -e)
if [ -e ${TMP_MBOX} ];then
	cat ${TMP_MBOX} >> ${LOG_DEST} && rm ${TMP_MBOX}
	echo "[i] Copied contents of 'mbox' to ${LOG_DEST}"
	exit 0
else
	echo "[i] Couldn't find file 'mbox' in your home dir. Aborting..."
	exit 1
fi
