#!/bin/bash
# bash script for putting wlan0
# into monitor mode.
# uses ifconfig, iwconfig, iw.
# requires root permissions (ie run as sudo).

service NetworkManager stop
service wpa_supplicant stop

ifconfig wlan0 down
macchanger -a wlan0
iw wlan0 set name wlan0mon
iw wlan0mon set type monitor
ifconfig wlan0mon up

# let the user know the script worked.
ifconfig wlan0mon
