#!/bin/bash
# bash script for putting wlan0mon
# back into managed mode.
# requires root permissions (ie run as sudo).

ifconfig wlan0mon down
iw wlan0mon set name wlan0
iw wlan1 set type managed
#ifconfig wlan0 hw c8:..:..:..:..?
macchanger -p wlan0
ifconfig wlan0 up
service NetworkManager start

