#!/bin/bash
# bash script for putting wlan0
# back into managed mode.
# uses ifconfig, iwconfig, iw.
# requires root permissions (ie run as sudo).

ifconfig wlan0 down
#iw wlan0mon set name wlan0
iw wlan0 set type managed
ifconfig wlan0 up
service NetworkManager start

## TODO
## instead of using NetworkManager,
## use iw & iw/ifconfig to connect
## to an ap gotten by argv or
## prompting the user for input.
## if this wasn't going on github,
## i would just hard-code my
## router's SSID & MAC address as
## args for iw (iw <interface> connect <SSID> <hwaddr> <passwd?>
## also, can't hard code or ask the user
## for wi-fi creds...
#iw wlan0 connect
