#!/bin/bash
# use macchanger to change hw address of wlan0.
# commented out: alternate method of changing
# an interface's hw address.
# 
# usage:
# ./spoofmac <interface>

sudo ifconfig $1 down
sudo macchanger -a $1
sudo ifconfig $1 up

# IW METHOD...
#sudo ifconfig wlan0 down
#sudo ifconfig wlan0 hw ether #xx:xx:xx:xx:xx:xx
#sudo ifconfig up
