#! /usr/bin/env bash

# Service Init Filter
# I used this on my raspberry pi4 as
# a 'nix n00b.
# 
# Proper way to set & unset services that start with
# the desktop on debian systems:
# >$ systemctl disable|enable <service>
# Guess i'll hang onto it; just in case.

echo "::SERVICE INIT FILTER::"
echo "-Stopping the following services:"
echo "-apache2, bluetooth, mysql, postgresql, tor"
echo "-This will take several seconds."

sudo service apache2 stop
sudo service bluetooth stop
sudo service mysql stop
sudo service postgresql stop
sudo service tor stop

# show list of services, their status,
# and exit. filter only these 5 services
# with grep.

service --status-all | grep -i -e apache2 -e bluetooth -e mysql -e postgresql -e tor
