#!/bin/bash
# ============================================== #
# TALKING-TO-MYSELF.SH - SHELL SCRIPT            #
# ============================================== #
# just for fun. might lead to some good ideas for#
# something later on.                            #
# clearly a lot of potential here.               #
# -----------------------------------------------#
# brianc2788@gmail.com                           #
# ---------------------------------------------- #

printbuf() {
	color=$1
	x=$2
	y=$3
	text=$4

	if [ $# -eq 4 ]
	then
	time=2.0
	clear
	tput setaf ${color};tput cup ${x} ${y};echo -n ${text}
	sleep ${time}
	else
		if [ $# -eq 5 ]
		then
			time=$5
			tput setaf ${color};tput cup ${x} ${y};echo -n ${text};sleep ${time}
		fi
	fi
}

#the "main event"
printbuf 1 10 20 "... talking to myself..."
printbuf 2 10 20 "huh? who're you? where is this?"
printbuf 1 10 20 "what do you mean?"
printbuf 2 10 20 "how are you doing this?"
printbuf 1 10 20 "doing what"
printbuf 1 10 30 "." 1
printbuf 1 10 31 "." 1
printbuf 1 10 32 "." 1

#outro
printbuf 7 10 40 "lol k."
printbuf 7 10 40 "you can go now."
clear
printbuf 7 10 40 "press ENTER" 0
read ${INPUT_BUFFER}
