#!/bin/bash
# ============================================== #
# TALKING-TO-MYSELF.SH - SHELL SCRIPT            #
# ============================================== #
# just for fun. might lead to some good ideas for#
# something later on.                            #
# clearly a lot of potential here.               #
# -----------------------------------------------#
# brianc2788@gmail.com                           #
# ---------------------------------------------- #

printbuf() {
	color=$1
	x=$2
	y=$3
	text=$4

	if [ $# -eq 4 ]
	then
	time=2.0
	clear
	tput setaf ${color};tput cup ${x} ${y};echo -n ${text}
	sleep ${time}
	else
		if [ $# -eq 5 ]
		then
			time=$5
			tput setaf ${color};tput cup ${x} ${y};echo -n ${text};sleep ${time}
		fi
	fi
}

#the "main event"
printbuf 1 10 20 "wake up, neo."
printbuf 1 10 20 "the matrix has you."
printbuf 1 10 20 "follow the white rabbit."
printbuf 1 10 20 "                        "
printbuf 1 10 20 "knock" 1
printbuf 1 10 30 "knock," 1
printbuf 1 10 40 "neo." 3
printbuf 1 12 30 "press ENTER"
read ${INPUT_BUFFER}
