#!/bin/bash
# Changes network interface back to it's
# original hw (MAC) address.
# Currently uses 'macchanger'.
# 
# usage:
# ./unspoofmac <interface>

sudo ifconfig $1 down
sudo macchanger -p $1
sudo ifconfig $1 up

# IW METHOD
#sudo ifconfig $1 down
#sudo ifconfig $1 hw ether #<perma-hw-addr>
#sudo ifconfig $1 up
