#!/bin/bash
# Wifi-Wardrive1
# Put the NIC in monitor mode
# and start airodump-ng & tshark.
# Writes to capture files (.cap).

#sudo service NetworkManager stop
#sudo service wpa_supplicant stop

sudo ifconfig wlan0 down
sudo macchanger -a wlan0
sudo iw wlan0 set type monitor
sudo ifconfig wlan0 up

DATE1=""
date +%m%d | read DATE1

sudo airodump-ng --output-format cap -w $DATE1 wlan0
#sudo tshark -i wlan0 -w /home/userone/tshark$DATE1.cap &

echo 'wlan0 in monitor mode. running airodump-ng & (!)tshark...'