#!/bin/bash
# Wifi-Wardrive1
# Put the NIC in monitor mode
# and start airodump-ng & tshark.
# Writes to capture files (.cap).

sudo service NetworkManager stop
sudo service wpa_supplicant stop

sudo ifconfig wlan0 down
sudo macchanger -a wlan0
sudo iw wlan0 set type monitor
sudo ifconfig wlan0 up

date +%b%d | read FILEDATE

#sudo airodump-ng wlan0 --output-format cap -w $FILEDATE
# I think, currently,
# airodump is not working and tshark is.
sudo tshark -i wlan0 -w /root/$FILEDATE-tshark.cap
