#!/bin/bash
# Wifi-Wardrive1
# Put the NIC in monitor mode
# and start airodump-ng & tshark.
# Writes to capture files (.cap).

sudo service NetworkManager stop
sudo service wpa_supplicant stop

sudo ifconfig wlan0 down
sudo macchanger -a wlan0
sudo iw wlan0 set type monitor
sudo ifconfig wlan0 up

FILENAME1=""
date +%m%d | read FILENAME1
FILEA1="$FILENAME1-adump.cap"
FILEB1="$FILENAME1-tshark.cap"


sudo airodump-ng wlan0 > $FILEA1 &
sudo tshark -i wlan0 > $FILEB1 &

echo 'wlan0 in monitor mode. running airodump-ng & tshark...'
