#!/bin/bash
# ===========================================
# wmanmode
# --------
# Personal-use shell script. quickly put the
# wifi NIC in managed mode with its original,
# "burned-in" hardware address (MAC). Restart
# NetworkManager service.
# --------
# Github:
# brianc2788@gmail.com
# https://user5260.github.io
# https://www.github.com/user5260/
# ===========================================

function usage() {
	echo -ne "Usage: $ wmanmode <iface>\nNeed a wireless interface to operate on.\n"
}

# If no arg, print usage.
if [ $# -lt 1 ];then
	usage
	exit 0
else
	NETIF=$1
	sudo ifconfig ${NETIF} down
	sudo iw ${NETIF} set type managed
	sudo macchanger -p ${NETIF}
	sudo ifconfig ${NETIF} up
	sudo service NetworkManager start
	# Using sudo on 'service' because it doesn't ask for a passw from polkit.
	# NetworkManager will restart wpa_supplicant.
fi
