#!/bin/bash
# ===========================================
# wmanmode
# --------
# Personal-use shell script. quickly put the
# wifi NIC in managed mode with its original,
# "burned-in" hardware address (MAC). Restart
# NetworkManager service.
# Commented out ifconfig & iw commands (deprecated)
# in favor of the ip gnu coreutil.
# Using GNU Macchanger for its ability to set the
# "locally-administered" bit for hw address.
# RESTORED ifconfig & iw commands.
# --------
# Github:
# brianc2788@gmail.com
# https://brianc2788.github.io
# https://github.com/brianc2788/bash
# ===========================================

function usage() {
	echo -ne "Usage: $ wmanmode <iface>\nNeed a wireless interface to operate on.\n"
}

# If no arg, print usage.
if [ $# -lt 1 ];then
	usage
	exit 0
else
	NETIF=$1
	sudo ifconfig ${NETIF} down
	#sudo ip link set ${NETIF} down
	sudo iw ${NETIF} set type managed
	#sudo ip link set ${NETIF} promisc off
	sudo macchanger -p ${NETIF}
	sudo ifconfig ${NETIF} up
	#sudo ip link set ${NETIF} up
	sudo service NetworkManager start
	# Using sudo on 'service' because it doesn't ask for a passw from polkit.
	# NetworkManager will restart wpa_supplicant.
	echo -ne "[!] ${NETIF} - Managed mode enabled.\n"
fi
