#!/bin/bash
# ===========================================
# wmonmode
# --------
# Personal-use shell script. quickly put the
# wifi NIC in monitor mode with a random MAC.
# Stop network services, change mac & mode on NIC.
# Depends: NetworkManager daemon, GNU Macchanger
# 
# -Commented out ifconfig (deprecated) for ip. Should do the same for iw.
# -Still using GNU Macchanger for -bia option.
#  Otherwise, "locally-administered address" bit gets set.
#  $ ip link set [device] address [address]
# --------
# Github:
# brianc2788@gmail.com
# https://user5260.github.io
# https://www.github.com/user5260/
# ===========================================

function usage() {
	echo -ne "Usage: $ wmonmode <iface>\nNeed a wireless interface to operate on.\n"
}

# If no args, print usage.
if [ $# -lt 1 ];then
	usage
	exit 0
else
	NETIF=$1
	sudo service NetworkManager stop
	sudo service wpa_supplicant stop
	#sudo ifconfig ${NETIF} down
	sudo ip link set ${NETIF} down
	sudo macchanger -br ${NETIF}
	sudo iw ${NETIF} set type monitor
	#sudo ifconfig ${NETIF} up
	sudo ip link set ${NETIF} up
	echo "[!] ${NETIF} - Monitor mode enabled."
fi
